### ISSUE TITLE
invalid Credentials thrown after a while

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#32]
Sorry for logging another one !

This one seems related to the cached credentials.
```
  File "g.py", line 61, in <module>
    recs += 1
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 896, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 868, in close
    self.flush(force=True)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 750, in flush
    self._simple_upload()
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 810, in _simple_upload
    validate_response(r, path)
  File "/usr/local/lib/python2.7/dist-packages/gcsfs/core.py", line 111, in validate_response
    raise RuntimeError(m)
RuntimeError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
```

I wonder if increasing the block size to say 50MB would not reduce the likehood of these error (overload, 'corrupted' credentials,...)

**Comment by martindurant** [comment]
GCSFS does not currently refresh tokens, so they probably expire after 3600s. Calling `gcs.connect()` or re-instantiating should fix this, and a check could be made in `_call()` to do so - although this had better be thread-safe.

**Comment by yiga2** [comment]
Exactly 60min after indeed ! 
My script will eventually be triggered at storage-upload events so only one zip to process but I was running a catch-up script. 
Will include logic to refresh the token. Thanks @martindurant !

**Comment by dbalabka** [comment]
@martindurant , the problem is still happening for us with version `2023.12.2.post1`:
```
File /opt/conda/lib/python3.10/site-packages/dask_expr/_expr.py:3727, in _execute_task()

File /opt/conda/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:97, in __call__()

File /opt/conda/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:645, in read_parquet_part()

File /opt/conda/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:646, in <listcomp>()

File /opt/conda/lib/python3.10/site-packages/dask/dataframe/io/parquet/arrow.py:641, in read_partition()

File /opt/conda/lib/python3.10/site-packages/dask/dataframe/io/parquet/arrow.py:1774, in _read_table()

File /opt/conda/lib/python3.10/site-packages/dask/dataframe/io/parquet/arrow.py:264, in _read_table_from_path()

File /opt/conda/lib/python3.10/site-packages/pyarrow/parquet/core.py:341, in __init__()

...

File /opt/conda/lib/python3.10/site-packages/fsspec/spec.py:1844, in read()

File /opt/conda/lib/python3.10/site-packages/fsspec/caching.py:69, in _fetch()

File /opt/conda/lib/python3.10/site-packages/gcsfs/core.py:1850, in _fetch_range()

File /opt/conda/lib/python3.10/site-packages/fsspec/asyn.py:118, in wrapper()

File /opt/conda/lib/python3.10/site-packages/fsspec/asyn.py:103, in sync()

File /opt/conda/lib/python3.10/site-packages/fsspec/asyn.py:56, in _runner()

File /opt/conda/lib/python3.10/site-packages/gcsfs/core.py:1027, in _cat_file()

File /opt/conda/lib/python3.10/site-packages/gcsfs/core.py:437, in _call()

File /opt/conda/lib/python3.10/site-packages/decorator.py:221, in fun()

File /opt/conda/lib/python3.10/site-packages/gcsfs/retry.py:158, in retry_request()

File /opt/conda/lib/python3.10/site-packages/gcsfs/retry.py:123, in retry_request()

File /opt/conda/lib/python3.10/site-packages/gcsfs/core.py:430, in _request()

File /opt/conda/lib/python3.10/site-packages/gcsfs/retry.py:112, in validate_response()
```
I belive adding extra logic for recreating the session toke in retry mechanism should help.

**Comment by dbalabka** [comment]
@yan-hic, can you please provide a way how you have recreated the session token?
